### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by Robertorosmaninho**
This PR is meant to be force-pushed to `master-update` or to `master`. It contains all the Pi2 optimizations tested, commit-by-commit, on top of the latest commit in the `rv-inc/evm-semantics:master` branch.
CI tests passing: https://github.com/Pi-Squared-Inc/evm-semantics/actions/runs/9849262351

### CODE REVIEW

**Comment by dwightguth** [comment]
This is not going to be merged. Furthermore, the diff itself is not that useful. I think it's good that we created a PR, but what we actually want to review is the interdiff between the old patch set and the new one.

This can be done, in this case, via the following command:

`git range-diff 4f2292b..475fa2f ecc16a8..c8a419a`

I used commit SHAs so this can be a permanent reference to this exact interdiff. What you're actually going to be running in practice is going to be:

`git range-diff v1.0.531..pi2/master origin/master..master-update`

The result is not going to particularly readable without colorization so I'm not going to share it here, but this is the version of the patch series that I reviewed. I will share comments on it below, if I have any.

**Comment by Robertorosmaninho** [comment]
Hey @dwightguth, I think the diff you're looking for is this: https://github.com/runtimeverification/evm-semantics/compare/master...Pi-Squared-Inc:evm-semantics:update-master

**Comment by dwightguth** [comment]
@Robertorosmaninho that is indeed the change we are pushing, but it's not particularly helpful to review. It shows the entire patch series we are pushing, which means we are effectively reviewing every single PR we already merged all over again. Over time, that doesn't scale.

What I am doing is reviewing the difference between two diffs: the old set of changes on the pi2/master branch, and the new set of changes on the pi2/master-update branch. By reviewing the *interdiff* of these two diffs, we see exactly what changes we are making to the PRs we merged in the past, no more and no less.

That's why I'm using the `git range-diff` command. There's not an easy way to view this on Github to my knowledge, however.

**Comment by dwightguth** [comment]
The patch set looks pretty good. I see you made a slightly different change to the test harness than I originally expected you would. That change doesn't affect production, but it could potentially affect the time to run the tests for development purposes. Right now I'm testing that there hasn't been a significant regression on that front. If there hasn't, I will initiate the force-push to master. If there has, I'll talk to you about exactly what I was kind of expecting here.

**Comment by dwightguth** [comment]
The changes I mentioned do indeed introduce a regression. Let me explain:

What the upstream change did was to make it so that instead of invoking the llvm backend once per json file, it invokes the llvm backend once per test case within the json file.

This is a rather significant performance regression. Take the case of test `BlockchainTests/GeneralStateTests/stTimeConsuming/sstore_combinations_initial01_2.json`, which has 1359 test cases within it.

On the `pi2/master` commit, which runs the entire json file in one llvm backend command, this test takes 7.6s to run. On the `master-update` commit, which splits the json into separate test cases and runs them individually, this takes 26.1s to run.

What I'd like for us to do is keep the old behavior: run the entire json file in one invocation of the llvm backend.

**Comment by ehildenb** [comment]
It's unclear to me why running the test-suite at max performance is important in this case. My understanding is that Pi2 cares about LLVM backend throughput, not about test-suite throughput. We're making the test-suite more granular so that we can compare performance of individual tests, and have better failure information on schedule updates. This is also so that we can upgrade the test-suite and only disable tests regarding new schedules instead of entire chunks of the test-suite.

I guess, if my assumption above that LLVM backend throughput is what's important and not test-suite throughput, then I'd suggest setting up a different testing harness to measure that (LLVM backend throughput) directly, because the test-suite is not the best metric. Even if the testing harness was optimized fully, the tests that are present there do not represent real-world throughput very well.

**Pull request closed without merging**
